#!/bin/bash

#SBATCH --nodes=2
#SBATCH --time=00:01:00
#SBATCH --qos=testing
#SBATCH --partition=shas-testing
#SBATCH --ntasks=24
#SBATCH --job-name=lsolve_time
#SBATCH --output=lsolve_time.%j.out

module purge
source /projects/jeka2967/profile.bash
export EASYCODE=/projects/jeka2967/src/Elemental/examples/lapack_like/
export EASYEXEC=/projects/jeka2967/src/Elemental/ompi-gcc8/bin/examples/lapack_like

mpirun -n 24 $EASYEXEC/LinearSolve --size 1024
